services:
  - type: web
    name: capital-trade-api
    runtime: python
    buildCommand: pip install fastapi uvicorn psycopg2-binary bcrypt python-jose pydantic-settings python-dotenv requests
    startCommand: uvicorn api_simple:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        scope: run
        value: ${DATABASE_URL}
      - key: ADMIN_USUARIO
        scope: run
        value: admin
      - key: ADMIN_PASSWORD
        scope: run
        value: ${ADMIN_PASSWORD}
      - key: SECRET_KEY
        scope: run
        generateValue: true
