"""
Datos iniciales de las principales universidades de España
Incluye universidades públicas y privadas de todas las comunidades autónomas
"""

UNIVERSIDADES_ESPANA = [
    # ============ COMUNIDAD DE MADRID ============
    {
        "nombre": "Universidad Complutense de Madrid",
        "siglas": "UCM",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "publica",
        "url_oficial": "https://www.ucm.es",
        "email_contacto": "informacion@ucm.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 1,
        "total_alumnos": 86000,
        "acepta_extranjeros": True,
        "requisitos_extranjeros": "Homologación de títulos, nivel B2 español, visa de estudiante"
    },
    {
        "nombre": "Universidad Politécnica de Madrid",
        "siglas": "UPM",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "publica",
        "url_oficial": "https://www.upm.es",
        "email_contacto": "informacion@upm.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 2,
        "total_alumnos": 38000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Autónoma de Madrid",
        "siglas": "UAM",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "publica",
        "url_oficial": "https://www.uam.es",
        "email_contacto": "informacion@uam.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 3,
        "total_alumnos": 30000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Carlos III de Madrid",
        "siglas": "UC3M",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "publica",
        "url_oficial": "https://www.uc3m.es",
        "email_contacto": "informacion@uc3m.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 5,
        "total_alumnos": 21000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Rey Juan Carlos",
        "siglas": "URJC",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "publica",
        "url_oficial": "https://www.urjc.es",
        "email_contacto": "informacion@urjc.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 15,
        "total_alumnos": 45000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "IE University",
        "siglas": "IE",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "privada",
        "url_oficial": "https://www.ie.edu",
        "email_contacto": "admissions@ie.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 1,  # Entre privadas
        "total_alumnos": 5000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Pontificia Comillas (ICAI-ICADE)",
        "siglas": "Comillas",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "privada",
        "url_oficial": "https://www.comillas.edu",
        "email_contacto": "informacion@comillas.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 2,
        "total_alumnos": 11000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Europea de Madrid",
        "siglas": "UEM",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "privada",
        "url_oficial": "https://universidadeuropea.com",
        "email_contacto": "informacion@universidadeuropea.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 5,
        "total_alumnos": 16000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Nebrija",
        "siglas": "Nebrija",
        "ciudad": "Madrid",
        "comunidad_autonoma": "Comunidad de Madrid",
        "tipo": "privada",
        "url_oficial": "https://www.nebrija.com",
        "email_contacto": "informacion@nebrija.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 8000,
        "acepta_extranjeros": True
    },

    # ============ CATALUÑA ============
    {
        "nombre": "Universidad de Barcelona",
        "siglas": "UB",
        "ciudad": "Barcelona",
        "comunidad_autonoma": "Cataluña",
        "tipo": "publica",
        "url_oficial": "https://www.ub.edu",
        "email_contacto": "informacio@ub.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 4,
        "total_alumnos": 62000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Autónoma de Barcelona",
        "siglas": "UAB",
        "ciudad": "Barcelona",
        "comunidad_autonoma": "Cataluña",
        "tipo": "publica",
        "url_oficial": "https://www.uab.cat",
        "email_contacto": "informacio@uab.cat",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 6,
        "total_alumnos": 40000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Politécnica de Cataluña",
        "siglas": "UPC",
        "ciudad": "Barcelona",
        "comunidad_autonoma": "Cataluña",
        "tipo": "publica",
        "url_oficial": "https://www.upc.edu",
        "email_contacto": "info@upc.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 7,
        "total_alumnos": 30000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Pompeu Fabra",
        "siglas": "UPF",
        "ciudad": "Barcelona",
        "comunidad_autonoma": "Cataluña",
        "tipo": "publica",
        "url_oficial": "https://www.upf.edu",
        "email_contacto": "informacio@upf.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 8,
        "total_alumnos": 12000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "ESADE Business School",
        "siglas": "ESADE",
        "ciudad": "Barcelona",
        "comunidad_autonoma": "Cataluña",
        "tipo": "privada",
        "url_oficial": "https://www.esade.edu",
        "email_contacto": "admissions@esade.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 3,
        "total_alumnos": 4000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Vic - Universidad Central de Cataluña",
        "siglas": "UVic-UCC",
        "ciudad": "Vic",
        "comunidad_autonoma": "Cataluña",
        "tipo": "privada",
        "url_oficial": "https://www.uvic.cat",
        "email_contacto": "informacio@uvic.cat",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 7000,
        "acepta_extranjeros": True
    },

    # ============ COMUNIDAD VALENCIANA ============
    {
        "nombre": "Universidad de Valencia",
        "siglas": "UV",
        "ciudad": "Valencia",
        "comunidad_autonoma": "Comunidad Valenciana",
        "tipo": "publica",
        "url_oficial": "https://www.uv.es",
        "email_contacto": "informacio@uv.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 9,
        "total_alumnos": 50000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Politécnica de Valencia",
        "siglas": "UPV",
        "ciudad": "Valencia",
        "comunidad_autonoma": "Comunidad Valenciana",
        "tipo": "publica",
        "url_oficial": "https://www.upv.es",
        "email_contacto": "informacion@upv.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 10,
        "total_alumnos": 37000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Alicante",
        "siglas": "UA",
        "ciudad": "Alicante",
        "comunidad_autonoma": "Comunidad Valenciana",
        "tipo": "publica",
        "url_oficial": "https://www.ua.es",
        "email_contacto": "informacion@ua.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 18,
        "total_alumnos": 27000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Jaume I",
        "siglas": "UJI",
        "ciudad": "Castellón",
        "comunidad_autonoma": "Comunidad Valenciana",
        "tipo": "publica",
        "url_oficial": "https://www.uji.es",
        "email_contacto": "info@uji.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 20,
        "total_alumnos": 14000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad Católica de Valencia",
        "siglas": "UCV",
        "ciudad": "Valencia",
        "comunidad_autonoma": "Comunidad Valenciana",
        "tipo": "privada",
        "url_oficial": "https://www.ucv.es",
        "email_contacto": "informacion@ucv.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 11000,
        "acepta_extranjeros": True
    },

    # ============ ANDALUCÍA ============
    {
        "nombre": "Universidad de Sevilla",
        "siglas": "US",
        "ciudad": "Sevilla",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.us.es",
        "email_contacto": "informacion@us.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 11,
        "total_alumnos": 65000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Granada",
        "siglas": "UGR",
        "ciudad": "Granada",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.ugr.es",
        "email_contacto": "informacion@ugr.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 12,
        "total_alumnos": 60000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Málaga",
        "siglas": "UMA",
        "ciudad": "Málaga",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.uma.es",
        "email_contacto": "informacion@uma.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 14,
        "total_alumnos": 40000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Córdoba",
        "siglas": "UCO",
        "ciudad": "Córdoba",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.uco.es",
        "email_contacto": "informacion@uco.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 22,
        "total_alumnos": 21000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Cádiz",
        "siglas": "UCA",
        "ciudad": "Cádiz",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.uca.es",
        "email_contacto": "informacion@uca.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 25,
        "total_alumnos": 20000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Almería",
        "siglas": "UAL",
        "ciudad": "Almería",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.ual.es",
        "email_contacto": "informacion@ual.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 13000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Jaén",
        "siglas": "UJA",
        "ciudad": "Jaén",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.ujaen.es",
        "email_contacto": "informacion@ujaen.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 16000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Huelva",
        "siglas": "UHU",
        "ciudad": "Huelva",
        "comunidad_autonoma": "Andalucía",
        "tipo": "publica",
        "url_oficial": "https://www.uhu.es",
        "email_contacto": "informacion@uhu.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 12000,
        "acepta_extranjeros": True
    },

    # ============ PAÍS VASCO ============
    {
        "nombre": "Universidad del País Vasco",
        "siglas": "UPV/EHU",
        "ciudad": "Bilbao",
        "comunidad_autonoma": "País Vasco",
        "tipo": "publica",
        "url_oficial": "https://www.ehu.eus",
        "email_contacto": "informazioa@ehu.eus",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 13,
        "total_alumnos": 47000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Deusto",
        "siglas": "Deusto",
        "ciudad": "Bilbao",
        "comunidad_autonoma": "País Vasco",
        "tipo": "privada",
        "url_oficial": "https://www.deusto.es",
        "email_contacto": "informacion@deusto.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 4,
        "total_alumnos": 12000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Mondragon Unibertsitatea",
        "siglas": "MU",
        "ciudad": "Mondragón",
        "comunidad_autonoma": "País Vasco",
        "tipo": "privada",
        "url_oficial": "https://www.mondragon.edu",
        "email_contacto": "info@mondragon.edu",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 4000,
        "acepta_extranjeros": True
    },

    # ============ GALICIA ============
    {
        "nombre": "Universidad de Santiago de Compostela",
        "siglas": "USC",
        "ciudad": "Santiago de Compostela",
        "comunidad_autonoma": "Galicia",
        "tipo": "publica",
        "url_oficial": "https://www.usc.es",
        "email_contacto": "informacion@usc.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 16,
        "total_alumnos": 27000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Vigo",
        "siglas": "UVigo",
        "ciudad": "Vigo",
        "comunidad_autonoma": "Galicia",
        "tipo": "publica",
        "url_oficial": "https://www.uvigo.gal",
        "email_contacto": "informacion@uvigo.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 19,
        "total_alumnos": 23000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de A Coruña",
        "siglas": "UDC",
        "ciudad": "A Coruña",
        "comunidad_autonoma": "Galicia",
        "tipo": "publica",
        "url_oficial": "https://www.udc.es",
        "email_contacto": "informacion@udc.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 24,
        "total_alumnos": 17000,
        "acepta_extranjeros": True
    },

    # ============ CASTILLA Y LEÓN ============
    {
        "nombre": "Universidad de Salamanca",
        "siglas": "USAL",
        "ciudad": "Salamanca",
        "comunidad_autonoma": "Castilla y León",
        "tipo": "publica",
        "url_oficial": "https://www.usal.es",
        "email_contacto": "informacion@usal.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 17,
        "total_alumnos": 30000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Valladolid",
        "siglas": "UVa",
        "ciudad": "Valladolid",
        "comunidad_autonoma": "Castilla y León",
        "tipo": "publica",
        "url_oficial": "https://www.uva.es",
        "email_contacto": "informacion@uva.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 21,
        "total_alumnos": 25000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de León",
        "siglas": "ULE",
        "ciudad": "León",
        "comunidad_autonoma": "Castilla y León",
        "tipo": "publica",
        "url_oficial": "https://www.unileon.es",
        "email_contacto": "informacion@unileon.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 14000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Burgos",
        "siglas": "UBU",
        "ciudad": "Burgos",
        "comunidad_autonoma": "Castilla y León",
        "tipo": "publica",
        "url_oficial": "https://www.ubu.es",
        "email_contacto": "informacion@ubu.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 8000,
        "acepta_extranjeros": True
    },

    # ============ OTRAS COMUNIDADES ============
    {
        "nombre": "Universidad de Zaragoza",
        "siglas": "UNIZAR",
        "ciudad": "Zaragoza",
        "comunidad_autonoma": "Aragón",
        "tipo": "publica",
        "url_oficial": "https://www.unizar.es",
        "email_contacto": "informacion@unizar.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 23,
        "total_alumnos": 32000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Murcia",
        "siglas": "UM",
        "ciudad": "Murcia",
        "comunidad_autonoma": "Región de Murcia",
        "tipo": "publica",
        "url_oficial": "https://www.um.es",
        "email_contacto": "informacion@um.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 34000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Navarra",
        "siglas": "UNAV",
        "ciudad": "Pamplona",
        "comunidad_autonoma": "Navarra",
        "tipo": "privada",
        "url_oficial": "https://www.unav.edu",
        "email_contacto": "informacion@unav.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "ranking_nacional": 6,
        "total_alumnos": 12000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Oviedo",
        "siglas": "UNIOVI",
        "ciudad": "Oviedo",
        "comunidad_autonoma": "Principado de Asturias",
        "tipo": "publica",
        "url_oficial": "https://www.uniovi.es",
        "email_contacto": "informacion@uniovi.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 25000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Cantabria",
        "siglas": "UC",
        "ciudad": "Santander",
        "comunidad_autonoma": "Cantabria",
        "tipo": "publica",
        "url_oficial": "https://www.unican.es",
        "email_contacto": "informacion@unican.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 12000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de La Rioja",
        "siglas": "UR",
        "ciudad": "Logroño",
        "comunidad_autonoma": "La Rioja",
        "tipo": "publica",
        "url_oficial": "https://www.unirioja.es",
        "email_contacto": "informacion@unirioja.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 7000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Extremadura",
        "siglas": "UEX",
        "ciudad": "Badajoz",
        "comunidad_autonoma": "Extremadura",
        "tipo": "publica",
        "url_oficial": "https://www.unex.es",
        "email_contacto": "informacion@unex.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 21000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Castilla-La Mancha",
        "siglas": "UCLM",
        "ciudad": "Ciudad Real",
        "comunidad_autonoma": "Castilla-La Mancha",
        "tipo": "publica",
        "url_oficial": "https://www.uclm.es",
        "email_contacto": "informacion@uclm.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 30000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de las Islas Baleares",
        "siglas": "UIB",
        "ciudad": "Palma",
        "comunidad_autonoma": "Islas Baleares",
        "tipo": "publica",
        "url_oficial": "https://www.uib.es",
        "email_contacto": "informacion@uib.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 16000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de La Laguna",
        "siglas": "ULL",
        "ciudad": "San Cristóbal de La Laguna",
        "comunidad_autonoma": "Canarias",
        "tipo": "publica",
        "url_oficial": "https://www.ull.es",
        "email_contacto": "informacion@ull.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 24000,
        "acepta_extranjeros": True
    },
    {
        "nombre": "Universidad de Las Palmas de Gran Canaria",
        "siglas": "ULPGC",
        "ciudad": "Las Palmas de Gran Canaria",
        "comunidad_autonoma": "Canarias",
        "tipo": "publica",
        "url_oficial": "https://www.ulpgc.es",
        "email_contacto": "informacion@ulpgc.es",
        "tiene_api": False,
        "metodo_scraping": "beautifulsoup",
        "total_alumnos": 22000,
        "acepta_extranjeros": True
    }
]
